train_seg2019.py:150: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight)
Traceback (most recent call last):
  File "train_seg2019.py", line 157, in <module>
    main()
  File "train_seg2019.py", line 106, in main
    train_loss = train(args, epoch, model, trainLoader, optimizer, batch_size)
  File "train_seg2019.py", line 126, in train
    output = model(img)
  File "/cluster/home/it_stu3/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu3/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/cluster/home/it_stu3/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/cluster/home/it_stu3/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/cluster/home/it_stu3/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/cluster/home/it_stu3/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu3/jackstark/StructSeg19-task1/vnet.py", line 189, in forward
    out = self.out_tr(out)
  File "/cluster/home/it_stu3/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu3/jackstark/StructSeg19-task1/vnet.py", line 137, in forward
    out = out.view(self.bs, self.classes, out[0].numel() // self.classes)
RuntimeError: shape '[16, 23, 884736]' is invalid for input of size 81395712
